import { Breadcrumb, Card, Row, Space } from "antd";
import Meta from "antd/lib/card/Meta";
import HomeProductCard from "../componenets/HomeProductCard";

export function Home() {
  return (
    <>
      <Breadcrumb style={{ margin: "16px 0" }}>
        <Breadcrumb.Item>Home</Breadcrumb.Item>
        <Breadcrumb.Item>List</Breadcrumb.Item>
        <Breadcrumb.Item>App</Breadcrumb.Item>
      </Breadcrumb>
      <div
        className="site-layout-background"
        style={{ padding: 24, minHeight: 380 }}
      >
        <Space size={"small"}>
          <HomeProductCard />
          <HomeProductCard />
        </Space>
      </div>
    </>
  );
}
export default Home;

const dummy = [
  {
    code: "H6588002_S_ST_Sony_Xperia1_64_JP_Black",
    name: "Xperia 1 6/64GB 平行進口 日本版 [3色]",
    url: "main/%E7%9B%9B%E9%80%B8%E7%99%BE%E8%B2%A8/s/H6588002/%E9%9B%BB%E5%AD%90%E9%9B%BB%E5%99%A8/%E9%9B%BB%E5%AD%90%E9%9B%BB%E5%99%A8/%E6%89%8B%E6%A9%9F-%E5%B9%B3%E6%9D%BF%E9%9B%BB%E8%85%A6/%E6%89%8B%E6%8F%90%E9%9B%BB%E8%A9%B1/Sony/Xperia-1-664GB-%E5%B9%B3%E8%A1%8C%E9%80%B2%E5%8F%A3-%E6%97%A5%E6%9C%AC%E7%89%88-3%E8%89%B2/p/H6588002_S_ST_Sony_Xperia1_64_JP_Black",
    description:
      "<h5>處理器<br/>Qualcomm® Snapdragon™ 855<br/><br/>記憶體<br/>6 GB RAM + 64 GB ROM/ 最高支援512GB MicroSD記憶咭<br/><br/>作業平台<br/>Android 9<br/><br/>螢幕<br/>6.5 吋  4K 1644x3840 21:9 CinemaWide HDR OLED 屏幕<br/><br/>電池<br/>3,330 mAh <br/><br/>主鏡頭 – 三鏡頭設計<br/>1200萬像素78度廣角鏡頭 F1.6 +<br/>1200萬像素130度超廣角鏡頭 F2.4 +<br/>1200萬像素 45度鏡頭 F2.4<br/>支援960fps超慢動作影片, 2倍光學變焦<br/><br/>前置鏡頭<br/>800萬像素鏡頭 F2.0 HDR<br/><br/>呎吋<br/>167 x 72 x 8.2毫米<br/><br/>重量<br/>178 g<br/><br/>網絡制式 - 單咭<br/>4G: LTE Band 1/3/8/11/28/42<br/>3G: Band 1/8<br/><br/>藍牙<br/>v5.0 <br/><br/>Wi-Fi<br/>IEEE 802.11a/b/g/n(2.4GHz)/n(5GHz)/ac<br/><br/>NFC<br/>支援<br/><br/></h5>",
    purchasable: true,
    stock: {
      stockLevelStatus: {
        code: "inStock",
        type: "StockLevelStatus",
      },
      stockLevel: 1,
      consignmentWarehouse: false,
      forceInStock: false,
    },
    numberOfReviews: 0,
    summary:
      "<h5>Softbank版, 型號: 802SO (已解鎖)<br/>4K 21:9 屏幕<br/>6GB + 64GB<br/>水貨7日保養,不設官方保養服務<br/><br/>不包含充電器及數據線<br/>盒內包含: 手機 x1, Typc-C to 3.5mm 轉接器 x1</h5>",
    price: {
      currencyIso: "HKD",
      value: 4698,
      priceType: "BUY",
      formattedValue: "$ 4,698.00",
      minQuantity: null,
      maxQuantity: null,
      membershipLevel: "NORMAL",
    },
    baseProduct: "H6588002ST_Sony_Xperia1_64_JP_Black",
    images: [
      {
        imageType: "PRIMARY",
        format: "product",
        url: "https://images.hktv-img.com/images/HKTV/18230/ST_Sony_Xperia1_64_JP_Black_main_44326701_20200626130911_01_300.jpg",
        altText: null,
        galleryIndex: null,
        width: null,
        hoverImageUrl: null,
      },
    ],
    categories: [
      {
        code: "AA32550525001",
        name: "Sony",
        url: null,
        description: null,
        image: null,
        parentCategoryName: null,
        sequence: 0,
      },
    ],
    potentialPromotions: [
      {
        code: "mms_percentage_discountH6588002_S_ST_Sony_Xperia1_64_JP_Black_sys",
        promotionType: "HktvProductPercentageDiscountPromotion",
        startDate: "2020-08-26T14:42:47+08:00",
        endDate: "2099-12-31T00:00:00+08:00",
        description: "Mms_FixedPrice_H6588002_S_ST_Sony_Xperia1_64_JP_Black",
        priority: 95,
        percentage: 32.31162,
        percentageDiscountRow: [
          {
            discount: 32.31162,
            customerType: "NORMAL",
            priority: 0,
            description: "Fixed price Discount (normal)",
          },
        ],
        creationTime: "2020-08-26T14:42:47+08:00",
      },
    ],
    variantOptions: [
      {
        code: "H6588002_S_ST_Sony_Xperia1_64_JP_White",
        stock: {
          consignmentWarehouse: false,
          forceInStock: false,
        },
        url: "main/%E7%9B%9B%E9%80%B8%E7%99%BE%E8%B2%A8/s/H6588002/%E9%9B%BB%E5%AD%90%E9%9B%BB%E5%99%A8/%E9%9B%BB%E5%AD%90%E9%9B%BB%E5%99%A8/%E6%89%8B%E6%A9%9F-%E5%B9%B3%E6%9D%BF%E9%9B%BB%E8%85%A6/%E6%89%8B%E6%8F%90%E9%9B%BB%E8%A9%B1/Sony/Xperia-1-664GB-%E7%99%BD%E8%89%B2-%E5%B9%B3%E8%A1%8C%E9%80%B2%E5%8F%A3-%E6%97%A5%E6%9C%AC%E7%89%88/p/H6588002_S_ST_Sony_Xperia1_64_JP_White",
        priceData: {
          currencyIso: "HKD",
          value: 4698,
          priceType: "BUY",
          formattedValue: "$ 4,698.00",
          minQuantity: null,
          maxQuantity: null,
          membershipLevel: "NORMAL",
        },
        variantOptionQualifiers: null,
        color: "WHITE",
        mainImage: {
          imageType: "PRIMARY",
          format: "product",
          url: "https://images.hktv-img.com/images/HKTV/18230/ST_Sony_Xperia1_64_JP_White_main_44326896_20200626131116_01_300.jpg",
          altText: null,
          galleryIndex: null,
          width: null,
          hoverImageUrl: null,
        },
        swatchImage: {
          imageType: "PRIMARY",
          format: "styleSwatch",
          url: "https://images.hktv-img.com/images/HKTV/18230/ST_Sony_Xperia1_64_JP_White_main_44326896_20200626131116_01_300.jpg",
          altText: null,
          galleryIndex: null,
          width: null,
          hoverImageUrl: null,
        },
        discountPrice: {
          currencyIso: "HKD",
          value: 3180,
          priceType: "DISCOUNT",
          formattedValue: "$ 3,180.00",
          minQuantity: null,
          maxQuantity: null,
          membershipLevel: null,
        },
        loyalityPoints: "0.0",
        promotionText: "",
        promotionStyle: "",
        productVideoString: "",
        packingSpec: "",
        countryOfOrigin: "泰國",
        fixedDeliveryDate: null,
        labels: [
          {
            type: "OFFER",
            name: "Fixed price Discount (normal)",
            amount: null,
            loyaltyPoint: null,
          },
          {
            type: "REBATE",
            name: "0% Rewards",
            amount: 0,
            loyaltyPoint: "0",
          },
        ],
        potentialPromotions: [
          {
            code: "mms_percentage_discountH6588002_S_ST_Sony_Xperia1_64_JP_White_sys",
            promotionType: "HktvProductPercentageDiscountPromotion",
            startDate: "2020-08-26T14:43:06+08:00",
            endDate: "2099-12-31T00:00:00+08:00",
            description:
              "Mms_FixedPrice_H6588002_S_ST_Sony_Xperia1_64_JP_White",
            priority: 95,
            percentage: 32.31162,
            percentageDiscountRow: [
              {
                discount: 32.31162,
                customerType: "NORMAL",
                priority: 0,
                description: "Fixed price Discount (normal)",
              },
            ],
            creationTime: "2020-08-26T14:43:06+08:00",
          },
        ],
        thresholdPromotion: null,
        bundlePromotion: null,
        priceList: [
          {
            currencyIso: "HKD",
            value: 4698,
            priceType: "BUY",
            formattedValue: "$ 4,698.00",
            minQuantity: null,
            maxQuantity: null,
            membershipLevel: "NORMAL",
          },
          {
            currencyIso: "HKD",
            value: 3180.0000923999996,
            priceType: "DISCOUNT",
            formattedValue: "$ 3,180.00",
            minQuantity: null,
            maxQuantity: null,
            membershipLevel: "NORMAL",
          },
        ],
        recommendedSellingPrice: null,
        savedPrice: [
          {
            currencyIso: "HKD",
            value: 1517.9999076000004,
            priceType: "DISCOUNT",
            formattedValue: "$ 1,518.00",
            minQuantity: null,
            maxQuantity: null,
            membershipLevel: "NORMAL",
          },
        ],
        perfectPartnerPromotion: null,
        buyMoreSaveMore: null,
      },
      {
        code: "H6588002_S_ST_Sony_Xperia1_64_JP_Purple",
        stock: {
          consignmentWarehouse: false,
          forceInStock: false,
        },
        url: "main/%E7%9B%9B%E9%80%B8%E7%99%BE%E8%B2%A8/s/H6588002/%E9%9B%BB%E5%AD%90%E9%9B%BB%E5%99%A8/%E9%9B%BB%E5%AD%90%E9%9B%BB%E5%99%A8/%E6%89%8B%E6%A9%9F-%E5%B9%B3%E6%9D%BF%E9%9B%BB%E8%85%A6/%E6%89%8B%E6%8F%90%E9%9B%BB%E8%A9%B1/Sony/Xperia-1-664GB-%E7%B4%AB%E8%89%B2-%E5%B9%B3%E8%A1%8C%E9%80%B2%E5%8F%A3-%E6%97%A5%E6%9C%AC%E7%89%88/p/H6588002_S_ST_Sony_Xperia1_64_JP_Purple",
        priceData: {
          currencyIso: "HKD",
          value: 4698,
          priceType: "BUY",
          formattedValue: "$ 4,698.00",
          minQuantity: null,
          maxQuantity: null,
          membershipLevel: "NORMAL",
        },
        variantOptionQualifiers: null,
        color: "PURPLE",
        mainImage: {
          imageType: "PRIMARY",
          format: "product",
          url: "https://images.hktv-img.com/images/HKTV/18230/ST_Sony_Xperia1_64_JP_Purple_main_44327106_20200626131302_01_300.jpg",
          altText: null,
          galleryIndex: null,
          width: null,
          hoverImageUrl: null,
        },
        swatchImage: {
          imageType: "PRIMARY",
          format: "styleSwatch",
          url: "https://images.hktv-img.com/images/HKTV/18230/ST_Sony_Xperia1_64_JP_Purple_main_44327106_20200626131302_01_300.jpg",
          altText: null,
          galleryIndex: null,
          width: null,
          hoverImageUrl: null,
        },
        discountPrice: {
          currencyIso: "HKD",
          value: 3180,
          priceType: "DISCOUNT",
          formattedValue: "$ 3,180.00",
          minQuantity: null,
          maxQuantity: null,
          membershipLevel: null,
        },
        loyalityPoints: "0.0",
        promotionText: "",
        promotionStyle: "",
        productVideoString: "",
        packingSpec: "",
        countryOfOrigin: "泰國",
        fixedDeliveryDate: null,
        labels: [
          {
            type: "OFFER",
            name: "Fixed price Discount (normal)",
            amount: null,
            loyaltyPoint: null,
          },
          {
            type: "REBATE",
            name: "0% Rewards",
            amount: 0,
            loyaltyPoint: "0",
          },
        ],
        potentialPromotions: [
          {
            code: "mms_percentage_discountH6588002_S_ST_Sony_Xperia1_64_JP_Purple_sys",
            promotionType: "HktvProductPercentageDiscountPromotion",
            startDate: "2020-08-26T14:43:21+08:00",
            endDate: "2099-12-31T00:00:00+08:00",
            description:
              "Mms_FixedPrice_H6588002_S_ST_Sony_Xperia1_64_JP_Purple",
            priority: 95,
            percentage: 32.31162,
            percentageDiscountRow: [
              {
                discount: 32.31162,
                customerType: "NORMAL",
                priority: 0,
                description: "Fixed price Discount (normal)",
              },
            ],
            creationTime: "2020-08-26T14:43:21+08:00",
          },
        ],
        thresholdPromotion: null,
        bundlePromotion: null,
        priceList: [
          {
            currencyIso: "HKD",
            value: 4698,
            priceType: "BUY",
            formattedValue: "$ 4,698.00",
            minQuantity: null,
            maxQuantity: null,
            membershipLevel: "NORMAL",
          },
          {
            currencyIso: "HKD",
            value: 3180.0000923999996,
            priceType: "DISCOUNT",
            formattedValue: "$ 3,180.00",
            minQuantity: null,
            maxQuantity: null,
            membershipLevel: "NORMAL",
          },
        ],
        recommendedSellingPrice: null,
        savedPrice: [
          {
            currencyIso: "HKD",
            value: 1517.9999076000004,
            priceType: "DISCOUNT",
            formattedValue: "$ 1,518.00",
            minQuantity: null,
            maxQuantity: null,
            membershipLevel: "NORMAL",
          },
        ],
        perfectPartnerPromotion: null,
        buyMoreSaveMore: null,
      },
      {
        code: "H6588002_S_ST_Sony_Xperia1_64_JP_Black",
        stock: {
          consignmentWarehouse: false,
          forceInStock: false,
        },
        url: "main/%E7%9B%9B%E9%80%B8%E7%99%BE%E8%B2%A8/s/H6588002/%E9%9B%BB%E5%AD%90%E9%9B%BB%E5%99%A8/%E9%9B%BB%E5%AD%90%E9%9B%BB%E5%99%A8/%E6%89%8B%E6%A9%9F-%E5%B9%B3%E6%9D%BF%E9%9B%BB%E8%85%A6/%E6%89%8B%E6%8F%90%E9%9B%BB%E8%A9%B1/Sony/Xperia-1-664GB-%E5%B9%B3%E8%A1%8C%E9%80%B2%E5%8F%A3-%E6%97%A5%E6%9C%AC%E7%89%88-3%E8%89%B2/p/H6588002_S_ST_Sony_Xperia1_64_JP_Black",
        priceData: {
          currencyIso: "HKD",
          value: 4698,
          priceType: "BUY",
          formattedValue: "$ 4,698.00",
          minQuantity: null,
          maxQuantity: null,
          membershipLevel: "NORMAL",
        },
        variantOptionQualifiers: null,
        color: "BLACK",
        mainImage: {
          imageType: "PRIMARY",
          format: "product",
          url: "https://images.hktv-img.com/images/HKTV/18230/ST_Sony_Xperia1_64_JP_Black_main_44326701_20200626130911_01_300.jpg",
          altText: null,
          galleryIndex: null,
          width: null,
          hoverImageUrl: null,
        },
        swatchImage: {
          imageType: "PRIMARY",
          format: "styleSwatch",
          url: "https://images.hktv-img.com/images/HKTV/18230/ST_Sony_Xperia1_64_JP_Black_main_44326701_20200626130911_01_300.jpg",
          altText: null,
          galleryIndex: null,
          width: null,
          hoverImageUrl: null,
        },
        discountPrice: {
          currencyIso: "HKD",
          value: 3180,
          priceType: "DISCOUNT",
          formattedValue: "$ 3,180.00",
          minQuantity: null,
          maxQuantity: null,
          membershipLevel: null,
        },
        loyalityPoints: "0.0",
        promotionText: "",
        promotionStyle: "",
        productVideoString: "",
        packingSpec: "",
        countryOfOrigin: "泰國",
        fixedDeliveryDate: null,
        labels: [
          {
            type: "OFFER",
            name: "Fixed price Discount (normal)",
            amount: null,
            loyaltyPoint: null,
          },
          {
            type: "REBATE",
            name: "0% Rewards",
            amount: 0,
            loyaltyPoint: "0",
          },
        ],
        potentialPromotions: [
          {
            code: "mms_percentage_discountH6588002_S_ST_Sony_Xperia1_64_JP_Black_sys",
            promotionType: "HktvProductPercentageDiscountPromotion",
            startDate: "2020-08-26T14:42:47+08:00",
            endDate: "2099-12-31T00:00:00+08:00",
            description:
              "Mms_FixedPrice_H6588002_S_ST_Sony_Xperia1_64_JP_Black",
            priority: 95,
            percentage: 32.31162,
            percentageDiscountRow: [
              {
                discount: 32.31162,
                customerType: "NORMAL",
                priority: 0,
                description: "Fixed price Discount (normal)",
              },
            ],
            creationTime: "2020-08-26T14:42:47+08:00",
          },
        ],
        thresholdPromotion: null,
        bundlePromotion: null,
        priceList: [
          {
            currencyIso: "HKD",
            value: 4698,
            priceType: "BUY",
            formattedValue: "$ 4,698.00",
            minQuantity: null,
            maxQuantity: null,
            membershipLevel: "NORMAL",
          },
          {
            currencyIso: "HKD",
            value: 3180.0000923999996,
            priceType: "DISCOUNT",
            formattedValue: "$ 3,180.00",
            minQuantity: null,
            maxQuantity: null,
            membershipLevel: "NORMAL",
          },
        ],
        recommendedSellingPrice: null,
        savedPrice: [
          {
            currencyIso: "HKD",
            value: 1517.9999076000004,
            priceType: "DISCOUNT",
            formattedValue: "$ 1,518.00",
            minQuantity: null,
            maxQuantity: null,
            membershipLevel: "NORMAL",
          },
        ],
        perfectPartnerPromotion: null,
        buyMoreSaveMore: null,
      },
      {
        code: "H6588002_S_ST_Sony_Xperia1_64_JP_Black",
        stock: {
          consignmentWarehouse: false,
          forceInStock: false,
        },
        url: "main/%E7%9B%9B%E9%80%B8%E7%99%BE%E8%B2%A8/s/H6588002/%E9%9B%BB%E5%AD%90%E9%9B%BB%E5%99%A8/%E9%9B%BB%E5%AD%90%E9%9B%BB%E5%99%A8/%E6%89%8B%E6%A9%9F-%E5%B9%B3%E6%9D%BF%E9%9B%BB%E8%85%A6/%E6%89%8B%E6%8F%90%E9%9B%BB%E8%A9%B1/Sony/Xperia-1-664GB-%E5%B9%B3%E8%A1%8C%E9%80%B2%E5%8F%A3-%E6%97%A5%E6%9C%AC%E7%89%88-3%E8%89%B2/p/H6588002_S_ST_Sony_Xperia1_64_JP_Black",
        priceData: {
          currencyIso: "HKD",
          value: 4698,
          priceType: "BUY",
          formattedValue: "$ 4,698.00",
          minQuantity: null,
          maxQuantity: null,
          membershipLevel: "NORMAL",
        },
        variantOptionQualifiers: null,
        color: "Default",
        mainImage: {
          imageType: "PRIMARY",
          format: "product",
          url: "https://images.hktv-img.com/images/HKTV/18230/ST_Sony_Xperia1_64_JP_Black_main_44326701_20200626130911_01_300.jpg",
          altText: null,
          galleryIndex: null,
          width: null,
          hoverImageUrl: null,
        },
        swatchImage: {
          imageType: "PRIMARY",
          format: "styleSwatch",
          url: "https://images.hktv-img.com/images/HKTV/18230/ST_Sony_Xperia1_64_JP_Black_main_44326701_20200626130911_01_300.jpg",
          altText: null,
          galleryIndex: null,
          width: null,
          hoverImageUrl: null,
        },
        discountPrice: {
          currencyIso: "HKD",
          value: 3180,
          priceType: "DISCOUNT",
          formattedValue: "$ 3,180.00",
          minQuantity: null,
          maxQuantity: null,
          membershipLevel: null,
        },
        loyalityPoints: "0.0",
        promotionText: "",
        promotionStyle: "",
        productVideoString: "",
        packingSpec: "",
        countryOfOrigin: "泰國",
        fixedDeliveryDate: null,
        labels: [
          {
            type: "OFFER",
            name: "Fixed price Discount (normal)",
            amount: null,
            loyaltyPoint: null,
          },
          {
            type: "REBATE",
            name: "0% Rewards",
            amount: 0,
            loyaltyPoint: "0",
          },
        ],
        potentialPromotions: [
          {
            code: "mms_percentage_discountH6588002_S_ST_Sony_Xperia1_64_JP_Black_sys",
            promotionType: "HktvProductPercentageDiscountPromotion",
            startDate: "2020-08-26T14:42:47+08:00",
            endDate: "2099-12-31T00:00:00+08:00",
            description:
              "Mms_FixedPrice_H6588002_S_ST_Sony_Xperia1_64_JP_Black",
            priority: 95,
            percentage: 32.31162,
            percentageDiscountRow: [
              {
                discount: 32.31162,
                customerType: "NORMAL",
                priority: 0,
                description: "Fixed price Discount (normal)",
              },
            ],
            creationTime: "2020-08-26T14:42:47+08:00",
          },
        ],
        thresholdPromotion: null,
        bundlePromotion: null,
        priceList: [
          {
            currencyIso: "HKD",
            value: 4698,
            priceType: "BUY",
            formattedValue: "$ 4,698.00",
            minQuantity: null,
            maxQuantity: null,
            membershipLevel: "NORMAL",
          },
          {
            currencyIso: "HKD",
            value: 3180.0000923999996,
            priceType: "DISCOUNT",
            formattedValue: "$ 3,180.00",
            minQuantity: null,
            maxQuantity: null,
            membershipLevel: "NORMAL",
          },
        ],
        recommendedSellingPrice: null,
        savedPrice: [
          {
            currencyIso: "HKD",
            value: 1517.9999076000004,
            priceType: "DISCOUNT",
            formattedValue: "$ 1,518.00",
            minQuantity: null,
            maxQuantity: null,
            membershipLevel: "NORMAL",
          },
        ],
        perfectPartnerPromotion: null,
        buyMoreSaveMore: null,
      },
    ],
    score: 1,
    brandName: "SONY",
    storeCode: "H6588002",
    storeCodeOriginal: "H6588002",
    storeName: "盛逸百貨",
    storeType: "frequent_delivery_store",
    storeTypeDisplay: "假期無休店",
    storeRating: 4,
    chineseLocaleActive: true,
    deliveryModeName: "HKTV Standard Delivery",
    deliveryModeCode: "hktv-standard-delivery",
    packingSpec: "",
    countryOfOrigin: "泰國",
    numberOfColors: 3,
    storeTC:
      "<p>本店將依照個人資料保護法相關規定保護您的個人資料﹐並遵守HKTVmall的私隱保護政策。如有任何爭議﹐商戶將保留最終決定權而毋須另行通知。因實際情況所限﹐HKTVmall與門市銷售價格、促銷活動、條件與限制有機會各為不同﹐一切條款只適用於HKTVmall。HKTVmall並不是此店所出售的貨品或服務的賣方或供應商。</p><p>HKTVmall並非商品或服務的賣方或供應商。HKTVmall負責管理網站、安排訂單處理過程及完成提供閣下透過HKTVmall向供應商訂購的商品或服務。透過HKTVmall購買的商品或服務須受商戶的條款及細則約束。對銷售及處理索賠或因閣下與商戶之間的合約引起的任何其他問題是商戶的責任。就購買優惠券方面，閣下除與優惠券的賣方訂立合約，當閣下使用優惠券同時也與實際提供商品或服務的商戶訂立合約。HKTVmall概不承擔任何因閣下透過HKTVmall購買任何商品，服務或優惠券可能直接或間接蒙受索賠，損失或損害的責任，不論如何造成（包括遺漏或疏忽）。我們也不接受因使用或依據透過HKTVmall獲取的信息的任何索賠，損失或損害承擔任何責任。確保透過HKTVmall獲得的任何產品，服務或信息滿足閣下的特定要求是閣下的全部責任。特別是美容服務，閣下務必注意，在決定購買前應確保了解該服務將如何進行方。如有疑問，閣下應諮詢專業顧問</p>",
    promotionPrice: {
      currencyIso: "HKD",
      value: 3180,
      priceType: "DISCOUNT",
      formattedValue: "$ 3,180.00",
      minQuantity: null,
      maxQuantity: null,
      membershipLevel: null,
    },
    labels: [
      {
        type: "OFFER",
        name: "Fixed price Discount (normal)",
        amount: null,
        loyaltyPoint: null,
      },
      {
        type: "REBATE",
        name: "0% Rewards",
        amount: 0,
        loyaltyPoint: "0",
      },
    ],
    loyaltyPoint: "0.0",
    priceList: [
      {
        currencyIso: "HKD",
        value: 4698,
        priceType: "BUY",
        formattedValue: "$ 4,698.00",
        minQuantity: null,
        maxQuantity: null,
        membershipLevel: "NORMAL",
      },
      {
        currencyIso: "HKD",
        value: 3180.0000923999996,
        priceType: "DISCOUNT",
        formattedValue: "$ 3,180.00",
        minQuantity: null,
        maxQuantity: null,
        membershipLevel: "NORMAL",
      },
    ],
    colors: [],
    promotionText: "",
    promotionStyle: "",
    invisible: false,
    savedPrice: [
      {
        currencyIso: "HKD",
        value: 1517.9999076000004,
        priceType: "DISCOUNT",
        formattedValue: "$ 1,518.00",
        minQuantity: null,
        maxQuantity: null,
        membershipLevel: "NORMAL",
      },
    ],
    productKeyword: "M52448",
    primaryCatCode: "AA32550525001",
    isFlashSale: false,
    isEcoupon: false,
    numberOfVariants: 3,
    isStockNotified: false,
    urgent: false,
    purchaseOption: 0,
    reservable: false,
    quantity: 0,
    userMax: 0,
    store: {
      code: "H6588002",
      name: "盛逸百貨",
    },
    deliveryLabel: {
      deliveryMode: "standard-delivery",
      name: "2日集運",
      bgColor: "#FFEBEE",
    },
    includeRemovalService: false,
    isInsurance: false,
    packingLength: 0,
    packingHeight: 0,
    packingDepth: 0,
  },
  {
    code: "H6588001_S_Sony_Xperia_1_Black",
    name: "Xperia 1 6GB+128GB 夜黑色 香港行貨",
    url: "main/%E8%BC%9D%E7%85%8C%E6%95%B8%E7%A2%BC%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/s/H6588001/%E9%9B%BB%E5%AD%90%E9%9B%BB%E5%99%A8/%E9%9B%BB%E5%AD%90%E9%9B%BB%E5%99%A8/%E6%89%8B%E6%A9%9F-%E5%B9%B3%E6%9D%BF%E9%9B%BB%E8%85%A6/%E6%89%8B%E6%8F%90%E9%9B%BB%E8%A9%B1/Sony/Xperia-1-6GB128GB-%E5%A4%9C%E9%BB%91%E8%89%B2-%E9%A6%99%E6%B8%AF%E8%A1%8C%E8%B2%A8/p/H6588001_S_Sony_Xperia_1_Black",
    description:
      "<p><span>處理器</span><br/> <span>Qualcomm® Snapdragon™ 855</span></p><p><span>記憶體</span><br/> 6 GB RAM + 128 GB ROM/ <span>最高支援</span><span>512GB MicroSD</span><span>記憶咭</span></p><p><span>作業平台</span><br/> Android 9</p><p><span>螢幕</span><br/> 6.5 <span>吋</span><span>  </span>4K 1644x3840 21:9 CinemaWide HDR OLED <span>屏幕</span></p><p><span>電池</span><br/> 3,330 mAh </p><p><span>主鏡頭</span> – <span>三鏡頭設計</span><br/> 1200<span>萬像素</span><span>78</span><span>度廣角鏡頭</span><span> F1.6 +<br/> 1200</span><span>萬像素</span><span>130</span><span>度超廣角鏡頭</span><span> F2.4 +<br/> 1200</span><span>萬像素</span><span> 45</span><span>度鏡頭</span><span> F2.4<br/> </span><span>支援</span><span>960fps</span><span>超慢動作影片</span><span>, 2</span><span>倍光學變焦</span></p><p><span>前置鏡頭</span><br/> <span>800</span><span>萬像素鏡頭</span><span> F2.0 HDR</span></p><p><span>呎吋</span><br/> 167 x 72 x 8.2<span>毫米</span></p><p><span>重量</span><br/> 178 g</p><p><span>網絡制式</span><br/> 4G: LTE Band 1/2/3/4/5/7/8/12/13/17/19/20/25/26/28/29/32/38/39/40/41/46/66<br/> 3G Band 1/2/4/5/6/8/19<br/> GSM: 850/900/1800/1900 MHz</p><p><span>藍牙</span><br/> v5.0 </p><p>Wi-Fi<br/> IEEE 802.11a/b/g/n(2.4GHz)/n(5GHz)/ac</p><p>NFC<br/> <span>支援</span><span></span></p><p><span>其他</span><span><br/> LDAC, DSEE HX, </span><span>指紋感應器</span><span>, IP65/68</span></p>",
    purchasable: true,
    stock: {
      stockLevelStatus: {
        code: "inStock",
        type: "StockLevelStatus",
      },
      stockLevel: 1,
      consignmentWarehouse: false,
      forceInStock: false,
    },
    numberOfReviews: 0,
    summary:
      "<p>6.5吋 4K 21:9 影院式屏幕<br/>支援960fps 超慢動作 2倍光學變焦 後置3鏡頭設計<br/>6GB RAM / 128GB ROM<br/>3,330mAh 電池容量, 配合Xperia調節性充電技術<br/>1年原廠保養, 7天有壞更換<br/></p>",
    price: {
      currencyIso: "HKD",
      value: 6998,
      priceType: "BUY",
      formattedValue: "$ 6,998.00",
      minQuantity: null,
      maxQuantity: null,
      membershipLevel: "NORMAL",
    },
    baseProduct: "H6588001Sony_Xperia_1_Black",
    images: [
      {
        imageType: "PRIMARY",
        format: "product",
        url: "https://images.hktv-img.com/images/HKTV/18230/Sony_Xperia_1_Black_main_26289936_20190604112824_01_300.jpg",
        altText: null,
        galleryIndex: null,
        width: null,
        hoverImageUrl: null,
      },
    ],
    categories: [
      {
        code: "AA32550525001",
        name: "Sony",
        url: null,
        description: null,
        image: null,
        parentCategoryName: null,
        sequence: 0,
      },
    ],
    potentialPromotions: [
      {
        code: "mms_percentage_discountH6588001_S_Sony_Xperia_1_Black_sys",
        promotionType: "HktvProductPercentageDiscountPromotion",
        startDate: "2020-08-04T14:47:33+08:00",
        endDate: "2099-12-31T00:00:00+08:00",
        description: "Mms_FixedPrice_H6588001_S_Sony_Xperia_1_Black",
        priority: 95,
        percentage: 29.99428,
        percentageDiscountRow: [
          {
            discount: 29.99428,
            customerType: "NORMAL",
            priority: 0,
            description: "Fixed price Discount (normal)",
          },
        ],
        creationTime: "2020-08-04T14:47:33+08:00",
      },
    ],
    variantOptions: [
      {
        code: "H6588001_S_Sony_Xperia_1_Black",
        stock: {
          consignmentWarehouse: false,
          forceInStock: false,
        },
        url: "main/%E8%BC%9D%E7%85%8C%E6%95%B8%E7%A2%BC%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/s/H6588001/%E9%9B%BB%E5%AD%90%E9%9B%BB%E5%99%A8/%E9%9B%BB%E5%AD%90%E9%9B%BB%E5%99%A8/%E6%89%8B%E6%A9%9F-%E5%B9%B3%E6%9D%BF%E9%9B%BB%E8%85%A6/%E6%89%8B%E6%8F%90%E9%9B%BB%E8%A9%B1/Sony/Xperia-1-6GB128GB-%E5%A4%9C%E9%BB%91%E8%89%B2-%E9%A6%99%E6%B8%AF%E8%A1%8C%E8%B2%A8/p/H6588001_S_Sony_Xperia_1_Black",
        priceData: {
          currencyIso: "HKD",
          value: 6998,
          priceType: "BUY",
          formattedValue: "$ 6,998.00",
          minQuantity: null,
          maxQuantity: null,
          membershipLevel: "NORMAL",
        },
        variantOptionQualifiers: null,
        color: "Default",
        mainImage: {
          imageType: "PRIMARY",
          format: "product",
          url: "https://images.hktv-img.com/images/HKTV/18230/Sony_Xperia_1_Black_main_26289936_20190604112824_01_300.jpg",
          altText: null,
          galleryIndex: null,
          width: null,
          hoverImageUrl: null,
        },
        swatchImage: {
          imageType: "PRIMARY",
          format: "styleSwatch",
          url: "https://images.hktv-img.com/images/HKTV/18230/Sony_Xperia_1_Black_main_26289936_20190604112824_01_300.jpg",
          altText: null,
          galleryIndex: null,
          width: null,
          hoverImageUrl: null,
        },
        discountPrice: {
          currencyIso: "HKD",
          value: 4899,
          priceType: "DISCOUNT",
          formattedValue: "$ 4,899.00",
          minQuantity: null,
          maxQuantity: null,
          membershipLevel: null,
        },
        loyalityPoints: "0.0",
        promotionText: "",
        promotionStyle: "",
        productVideoString: "",
        packingSpec: "",
        countryOfOrigin: "中國",
        fixedDeliveryDate: null,
        labels: [
          {
            type: "OFFER",
            name: "Fixed price Discount (normal)",
            amount: null,
            loyaltyPoint: null,
          },
          {
            type: "REBATE",
            name: "0% Rewards",
            amount: 0,
            loyaltyPoint: "0",
          },
        ],
        potentialPromotions: [
          {
            code: "mms_percentage_discountH6588001_S_Sony_Xperia_1_Black_sys",
            promotionType: "HktvProductPercentageDiscountPromotion",
            startDate: "2020-08-04T14:47:33+08:00",
            endDate: "2099-12-31T00:00:00+08:00",
            description: "Mms_FixedPrice_H6588001_S_Sony_Xperia_1_Black",
            priority: 95,
            percentage: 29.99428,
            percentageDiscountRow: [
              {
                discount: 29.99428,
                customerType: "NORMAL",
                priority: 0,
                description: "Fixed price Discount (normal)",
              },
            ],
            creationTime: "2020-08-04T14:47:33+08:00",
          },
        ],
        thresholdPromotion: null,
        bundlePromotion: null,
        priceList: [
          {
            currencyIso: "HKD",
            value: 6998,
            priceType: "BUY",
            formattedValue: "$ 6,998.00",
            minQuantity: null,
            maxQuantity: null,
            membershipLevel: "NORMAL",
          },
          {
            currencyIso: "HKD",
            value: 4899.000285599999,
            priceType: "DISCOUNT",
            formattedValue: "$ 4,899.00",
            minQuantity: null,
            maxQuantity: null,
            membershipLevel: "NORMAL",
          },
        ],
        recommendedSellingPrice: null,
        savedPrice: [
          {
            currencyIso: "HKD",
            value: 2098.999714400001,
            priceType: "DISCOUNT",
            formattedValue: "$ 2,099.00",
            minQuantity: null,
            maxQuantity: null,
            membershipLevel: "NORMAL",
          },
        ],
        perfectPartnerPromotion: null,
        buyMoreSaveMore: null,
      },
    ],
    score: 1,
    brandName: "SONY",
    storeCode: "H6588001",
    storeCodeOriginal: "H6588001",
    storeName: "輝煌數碼",
    storeType: "trustworthy_store",
    storeTypeDisplay: "信譽優良店",
    storeRating: 4.5,
    chineseLocaleActive: true,
    deliveryModeName: "Merchant Delivery",
    deliveryModeCode: "merchant-delivery",
    packingSpec: "",
    countryOfOrigin: "中國",
    storeTC:
      "<p>本店將依照個人資料( 私隱) 條例相關規定保護您的個人資料, 並遵守HKTVmall 的私隱保護政策。</p><p>商品顏色或會因各種因素差異會略有不同, 一切以實物為準。</p><p>因實際情況所限,HKTVmall 與門市銷售價格、促銷活動、條件與限制有機會各為不同, 一切條款只適用於HKTVmall。</p><p>如有任何爭議, 商戶將保留最終決定權而毋須另行通知。</p><p>HKTVmall並不是此店所出售的貨品或服務的賣方或供應商。</p>",
    promotionPrice: {
      currencyIso: "HKD",
      value: 4899,
      priceType: "DISCOUNT",
      formattedValue: "$ 4,899.00",
      minQuantity: null,
      maxQuantity: null,
      membershipLevel: null,
    },
    labels: [
      {
        type: "OFFER",
        name: "Fixed price Discount (normal)",
        amount: null,
        loyaltyPoint: null,
      },
      {
        type: "REBATE",
        name: "0% Rewards",
        amount: 0,
        loyaltyPoint: "0",
      },
    ],
    loyaltyPoint: "0.0",
    priceList: [
      {
        currencyIso: "HKD",
        value: 6998,
        priceType: "BUY",
        formattedValue: "$ 6,998.00",
        minQuantity: null,
        maxQuantity: null,
        membershipLevel: "NORMAL",
      },
      {
        currencyIso: "HKD",
        value: 4899.000285599999,
        priceType: "DISCOUNT",
        formattedValue: "$ 4,899.00",
        minQuantity: null,
        maxQuantity: null,
        membershipLevel: "NORMAL",
      },
    ],
    colors: [],
    promotionText: "",
    promotionStyle: "",
    invisible: false,
    savedPrice: [
      {
        currencyIso: "HKD",
        value: 2098.999714400001,
        priceType: "DISCOUNT",
        formattedValue: "$ 2,099.00",
        minQuantity: null,
        maxQuantity: null,
        membershipLevel: "NORMAL",
      },
    ],
    productKeyword: "I35268",
    primaryCatCode: "AA32550525001",
    isFlashSale: false,
    isEcoupon: false,
    numberOfVariants: 1,
    isStockNotified: false,
    urgent: false,
    purchaseOption: 0,
    reservable: false,
    quantity: 0,
    userMax: 0,
    store: {
      code: "H6588001",
      name: "輝煌數碼",
    },
    deliveryLabel: {
      deliveryMode: "merchant-delivery",
      name: "商戶派送",
      bgColor: "#E1F5FE",
    },
    includeRemovalService: false,
    isInsurance: false,
    packingLength: 0,
    packingHeight: 0,
    packingDepth: 0,
  },
];
